Add Arabic translation
Ryochan7/DS4Windows pull request #1607
Opened 2020-11-29 19:53 UTC by xLive

2020-11-30 00:23 UTC, Zeddyx0 commented
I can help with that

2020-12-05 15:15 UTC, AnessZurba requested changes
Hi,
I'm a regular user of this app. Thanks for taking to the time to translate it to Arabic
Had some small suggestions if you don't mind

2020-12-05 15:15 UTC, AnessZurba commented on DS4Windows/Translations/Strings.ar.resx
> +    <value>تسريع</value>
تسارع\التسارع

2020-12-05 15:15 UTC, AnessZurba commented on DS4Windows/Translations/Strings.ar.resx
> +    <value>إضافة برنامج</value>
إضافة برامج

2020-12-05 15:15 UTC, AnessZurba commented on DS4Windows/Translations/Strings.ar.resx
> +    <value>ملفات التعريف تلقائية</value>
ملفات التعريف التلقائية\ملفات تعريف تلقائية

2020-12-05 15:15 UTC, AnessZurba commented on DS4Windows/Translations/Strings.ar.resx
> +    <value>الإغلاق مصغراً</value>
تصغير البرنامج عند إغلاقه

2020-12-05 15:15 UTC, AnessZurba commented on DS4Windows/Translations/Strings.ar.resx
> +    <value>إخفاء الغير محددة</value>
"إخفاء العناصر غير المحددة"
what do you think?

2020-12-05 16:45 UTC, xLive commented
> 
> 
> Hi,
> I'm a regular user of this app. Thanks for taking to the time to translate it to Arabic
> Had some small suggestions if you don't mind

LGTM thank you!

2020-12-12 18:32 UTC, merged

2020-12-12 18:49 UTC, Ryochan7 commented
Thank you for the translation